appName: adservice
appImage: gcr.io/google-samples/microservices-demo/adservice
appVersion: v0.2.3
appReplicas: 3
containerPort: 9555
containerEnvVars:
- name: PORT
  value: "9555"

servicePort: 9555
